### ISSUE TITLE
Tip darkmode

### ISSUE THREAD

**Issue by Anna-Kyra** [KaanKalmi/S10-enhanced-website#2]
```CSS
  &.element-water {
    --background-img-back-earth: url('/images/Underwater\ world_background.jpg');
    --background-img-front-earth: url('/images/Underwater\ world-front.jpg');
    --color-earth: #10315F;
    --element-symbol: url('/images/icons/water.png');
    --element-symbol-atk: url('/images/icons/water.png');
  }
```

[Primalink voorbeeld](https://github.com/Anna-Kyra/connect-your-tribe-profile-card/blob/18affffd5ee249c246976a81f58e8d826613af4d/public/style.css#L55-L61)

Je kan ipv andere properties aanmaken voor je light/dark mode de properties veranderen. Zie voorbeeld hierboven.
Met de knop kan je van class switchen meet behulp van javascript
